### ISSUE TITLE
Error Compiling: lto-wrapper failed

### ISSUE THREAD

**Issue by menehune23** [city41/ardynia#6]
Hello, I've noticed that when compiling the latest release (using Arduino IDE 1.8.15), I get the following compiler error. It only seems to pop up for this game, so I'm not sure what's going on.

```
/Users/andrewmeyer/Google Drive/Arduboy Games/ardynia/src/loadEntity.cpp: In function 'loadEntity(Entity&, unsigned char) [clone .part.0]':
/Users/andrewmeyer/Google Drive/Arduboy Games/ardynia/src/entityTemplates.h:49:23: error: variable 'entityProperties' with dynamic initialization put into program memory area
 const uint8_t PROGMEM entityProperties[NUM_ENTITIES * NUM_ENTITY_PROPS] = {
                       ^
lto-wrapper: fatal error: /Applications/Arduino.app/Contents/Java/hardware/tools/avr/bin/avr-gcc returned 1 exit status
compilation terminated.
/Applications/Arduino.app/Contents/Java/hardware/tools/avr/bin/../lib/gcc/avr/7.3.0/../../../../avr/bin/ld: error: lto-wrapper failed
collect2: error: ld returned 1 exit status
```

**Comment by city41** [comment]
Weird, I can't reproduce the error and it compiles fine for me on 1.8.15.

Can you try going to `src/entityTypes.h`, line 48, and change it from this:

```
const uint8_t NUM_ENTITIES = TORCH + 1;
```

to this

```
const uint8_t NUM_ENTITIES = 25;
```

And see if that fixes it?

**Comment by menehune23** [comment]
Thanks for the fast response! Unfortunately that doesn't fix it :( I'm on macOS 11.4 if that helps.

**Comment by menehune23** [comment]
I also tried changing the array size to a literal 100 (based on num props = 4, num entities = 25), but still get the same complaint:

```
/Users/andrewmeyer/Google Drive/Arduboy Games/ardynia/src/loadEntity.cpp: In function 'loadEntity(Entity&, unsigned char) [clone .part.0]':
/Users/andrewmeyer/Google Drive/Arduboy Games/ardynia/src/entityTemplates.h:49:23: error: variable 'entityProperties' with dynamic initialization put into program memory area
 const uint8_t PROGMEM entityProperties[/*NUM_ENTITIES * NUM_ENTITY_PROPS*/ 100] = {
                       ^
lto-wrapper: fatal error: /Applications/Arduino.app/Contents/Java/hardware/tools/avr/bin/avr-gcc returned 1 exit status
compilation terminated.
/Applications/Arduino.app/Contents/Java/hardware/tools/avr/bin/../lib/gcc/avr/7.3.0/../../../../avr/bin/ld: error: lto-wrapper failed
collect2: error: ld returned 1 exit status
```

**Comment by city41** [comment]
Which branch are you using? The line `const uint8_t PROGMEM entityProperties...` should be `constexpr uint8_t PROGMEM entityProperties...`.

I think that's why I can compile and you can't. I'm not sure what version of the code you are using. Can you try the master branch?

**Comment by city41** [comment]
Ah I see, "latest release" in your first message. Ok, that's the problem. If you can pull down the master branch it should compile ok.

**Comment by city41** [comment]
If you don't want to use git, you can get a zip of the master branch by clicking on the "get code" button on the main page and choosing zip.

**Comment by menehune23** [comment]
That worked, thanks! I'm guessing your next release will include this fix? Thanks again

**Comment by city41** [comment]
Glad it worked! I just deleted all the releases, as master is the best way to get the latest code. Thanks for bringing this to my attention.
